spring:
  application:
    name: parnas-service
  datasource:
    url: jdbc:postgresql://localhost:5432/parnas
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
  liquibase:
    change-log: classpath:liquibase/changelog-master.yaml
    enabled: true

server:
  port: 8080
  servlet:
    context-path: /api/v1

logging:
  pattern:
    level: "%5p [requestId:%X{requestId:-}]"
  level:
    org.example.parnasservice: INFO

parnas:
  jwt:
    access-token-expiration: 900
    refresh-token-expiration: 604800
    secret: p3K8xJ2mN5qR7vT9wY1bC4dF6gH0jL3nP6sU8vW2xZ5aB7cE9fI1kM4oR7tY0u
  platform:
    name: Parnas
  blockchain:
    enabled: true
    rpc-url: http://localhost:8545
    chain-id: 31337
    network: local
    required-confirmations: 1
    gas-limit: 3000000
    factory-address:
    deployer-private-key: 0x59c6995e998f97a5a0044966f094538a2c0a3bb26a0df09c9977e7805d9b83b6d

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
